name: build_and_push_containers

on:
  push:
    branches: develop

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.RS_PAT }}
      - 
        name: Build BWA 0.7.17 and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bwa_mem_0.7.17/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/bwa:0.7.17
      - 
        name: Build ABRA2 2.22 and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./abra2_2.22/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/abra2:2.22
      - 
        name: Build bedtools 2.28 and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./abra2_2.22/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/abra2:2.22



