name: build_and_push_containers

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**.cwl'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**.cwl'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        #if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.RS_PAT }}
      - name: Fetch releases
        run: |
          curl -X POST \
            -s \
            -H "Accept: application/vnd.github.package-deletes-preview+json" \
            -H "Authorization: bearer ${{ secrets.RS_PAT }}" \
            -d '{"query":"query {repository(owner:\"${{ GITHUB_ACTOR }}\", name:\"${{ GITHUB_REPOSITORY }}\") {registryPackages(last:10) {edges{node{id, name, versions(last:100){edges {node {id, updatedAt, version}}}}}}}}"}' \
            -o /tmp/response.json \
            --url https://api.github.com/graphql
      - name: Filter Releases
        run: "cat /tmp/response.json | jq -r 'def daysAgo(days): (now | floor) - (days * 86400); [.data.repository.registryPackages.edges[0].node.versions.edges | sort_by(.node.updatedAt|fromdate) | reverse | .[] | select( .node.version != \"docker-base-layer\" ) | .value[].node.id] | unique_by(.) | @csv'  | cut -d, -f1  | sed -e 's/^\"//' -e 's/\"$//' > /tmp/release.json"
      - name: Show Release
        id: release
        run: printf "::set-output name=id::%s" $(cat /tmp/release.json)
      - name: Delete Release
        uses: WyriHaximus/github-action-delete-package@master
        if: steps.release.outputs.id != ''
        with:
          packageVersionId: ${{ steps.release.outputs.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get Manifest
        id: manifest
        run: |
          echo ::set-output name=abra2::$(docker buildx imagetools inspect ghcr.io/msk-access/abra2:2.22 | jq '.')
          echo ::set-output name=manta::$(docker buildx imagetools inspect ghcr.io/msk-access/manta:1.5.1 | jq '.')
          echo ::set-output name=marianas::$(docker buildx imagetools inspect ghcr.io/msk-access/marianas:1.8.1 | jq '.')
          echo ::set-output name=bwa::$(docker buildx imagetools inspect ghcr.io/msk-access/bwa:0.7.17 | jq '.')
          echo ::set-output name=merge_fastq::$(docker buildx imagetools inspect ghcr.io/msk-access/merge_fastq:0.1.7 | jq '.')
          echo ::set-output name=fgbio_postprocessing::$(docker buildx imagetools inspect ghcr.io/msk-access/fgbio-postprocessing:0.2.1 | jq '.')
          echo ::set-output name=mutect::$(docker buildx imagetools inspect ghcr.io/msk-access/mutect:1.1.5 | jq '.')
          echo ::set-output name=trim_galore::$(docker buildx imagetools inspect ghcr.io/msk-access/trim_galore:0.6.2 | jq '.')
          echo ::set-output name=waltz::$(docker buildx imagetools inspect ghcr.io/msk-access/waltz:3.2.0 | jq '.')
      - 
        name: Build merge_fastq 0.1.7 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.merge_fastq }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./merge_fastq_0.1.7/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/merge_fastq:0.1.7
      - 
        name: Build BWA 0.7.17 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.bwa }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bwa_mem_0.7.17/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/bwa:0.7.17
      - 
        name: Build ABRA2 2.22 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.abra2 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./abra2_2.22/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/abra2:2.22
      - 
        name: Build MuTect 1.1.5 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.mutect }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./mutect_1.1.5/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/mutect:1.1.5
      - 
        name: Build Trim Galore 0.6.2 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.trim_galore }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./trim_galore_0.6.2/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/trim_galore:0.6.2
      - 
        name: Build Waltz 3.2.0 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.waltz }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./waltz_count_reads_3.1.1/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/waltz:3.2.0
      - 
        name: Build Marianas 1.8.1 and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.marianas }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./marianas_process_loop_umi_1.8.1/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/marianas:1.8.1
      - 
        name: Build Manta and Push to GitHub Packages
        if: ${{ !steps.manifest.outputs.manta }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./manta_1.5.1/container/Dockerfile
          push: true
          tags: |
            ghcr.io/msk-access/manta:1.5.1




