name: bwa_0.7.17

on:
  push:
    branches: develop

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bwa_mem_0.7.17/container/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: msk-access/bwa:0.7.17
          registry: ghcr.io
          username: "rhshah"
          password: ${{ secrets.PAT_RONAK }}
          repository: msk-access/cwl_commandlinetools

