name: bwa_0.7.17

on:
  push:
    branches: develop

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bwa_mem_0.7.17/container/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: msk-access/bwa:0.7.17
          registry: docker.pkg.github.co
          secrets: ${{ secrets.PAT_RONAK }}
          repository: msk-access/cwl_commandlinetools

